# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_ac_global_optspecs
    string join \n json q/quiet no-color h/help V/version
end

function __fish_ac_needs_command
    # Figure out if the current invocation already has a command.
    set -l cmd (commandline -opc)
    set -e cmd[1]
    argparse -s (__fish_ac_global_optspecs) -- $cmd 2>/dev/null
    or return
    if set -q argv[1]
        # Also print the command, so this can be used to figure out what it is.
        echo $argv[1]
        return 1
    end
    return 0
end

function __fish_ac_using_subcommand
    set -l cmd (__fish_ac_needs_command)
    test -z "$cmd"
    and return 1
    contains -- $cmd[1] $argv
end

complete -c ac -n "__fish_ac_needs_command" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_needs_command" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_needs_command" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_needs_command" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_needs_command" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_needs_command" -f -a "ls" -d 'List the projects ac can see'
complete -c ac -n "__fish_ac_needs_command" -f -a "status" -d 'Daemon state, supervisor state, and the status of every project'
complete -c ac -n "__fish_ac_needs_command" -f -a "daemon" -d 'Inspect or stop the container daemon'
complete -c ac -n "__fish_ac_needs_command" -f -a "images" -d 'Every image in the local image store'
complete -c ac -n "__fish_ac_needs_command" -f -a "df" -d 'Disk usage for images, containers and volumes'
complete -c ac -n "__fish_ac_needs_command" -f -a "prune" -d 'Remove stopped containers and unused images'
complete -c ac -n "__fish_ac_needs_command" -f -a "config" -d 'Print the resolved ac configuration (~/.config/ac/config.json)'
complete -c ac -n "__fish_ac_needs_command" -f -a "schema" -d 'Print the JSON Schema for a project manifest'
complete -c ac -n "__fish_ac_needs_command" -f -a "completions" -d 'Generate a shell completion script'
complete -c ac -n "__fish_ac_needs_command" -f -a "version" -d 'Print the ac version'
complete -c ac -n "__fish_ac_needs_command" -f -a "project" -d 'Run an action against a project'
complete -c ac -n "__fish_ac_needs_command" -f -a "__supervise" -d 'The detached supervisor loop. Not for direct use'
complete -c ac -n "__fish_ac_using_subcommand ls" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand ls" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand ls" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand ls" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand ls" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand status" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand status" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand status" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand status" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -f -a "status" -d 'Show whether the daemon is running and who owns it'
complete -c ac -n "__fish_ac_using_subcommand daemon; and not __fish_seen_subcommand_from status stop" -f -a "stop" -d 'Stop the daemon, but only if ac started it'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from status" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from status" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from status" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from status" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from status" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from stop" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from stop" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from stop" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand daemon; and __fish_seen_subcommand_from stop" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand images" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand images" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand images" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand images" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand images" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand df" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand df" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand df" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand df" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand df" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand prune" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand prune" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand prune" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand prune" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand prune" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand config" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand config" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand config" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand config" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand config" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand schema" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand schema" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand schema" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand schema" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand schema" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand completions" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand completions" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand completions" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand completions" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand completions" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand version" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand version" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand version" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand version" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand version" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "start" -d 'Start services, creating them if needed'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "stop" -d 'Stop services, keeping the containers for a fast restart'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "down" -d 'Stop AND remove containers. Named volumes and their data survive'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "restart" -d 'Stop then start services'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "ls" -d 'Per-service state, IP and published ports'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "logs" -d 'Show or follow logs'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "exec" -d 'Run a command inside a service'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "sh" -d 'Open an interactive shell inside a service'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "stats" -d 'Live resource usage'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "inspect" -d 'Full container JSON, straight from the daemon'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "kill" -d 'Send a signal to services'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "rm" -d 'Force remove containers, leaving named volumes intact'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "cp" -d 'Copy files to or from a service'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "pull" -d 'Pre-pull images so a later start is fast'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "images" -d 'Images this project\'s services use, from the manifest'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "port" -d 'Published port mappings declared in the manifest'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "ip" -d 'Container IPs, as reported by the daemon'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "env" -d 'Environment variables a service is started with, from the manifest'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "build" -d 'Build the project\'s images'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "login" -d 'Authenticate to the project\'s private registries'
complete -c ac -n "__fish_ac_using_subcommand project; and not __fish_seen_subcommand_from start stop down restart ls logs exec sh stats inspect kill rm cp pull images port ip env build login config" -a "config" -d 'Print the project manifest as written'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -l recreate -d 'Delete and recreate containers instead of restarting them in place. Named volumes and their data survive'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from start" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stop" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stop" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stop" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stop" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stop" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from down" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from down" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from down" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from down" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from down" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -l recreate -d 'Recreate rather than restart in place on the way back up'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from restart" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ls" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ls" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ls" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ls" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ls" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -s n -l tail -d 'Number of lines to show from the end of the logs' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -s f -l follow -d 'Follow log output'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -l boot -d 'Show the VM boot log instead of the container\'s stdio'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from logs" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from exec" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from exec" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from exec" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from exec" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from exec" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from sh" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from sh" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from sh" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from sh" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from sh" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stats" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stats" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stats" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stats" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from stats" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from inspect" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from inspect" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from inspect" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from inspect" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from inspect" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -s s -l signal -d 'Signal name, without the SIG prefix' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from kill" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from rm" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from rm" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from rm" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from rm" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from cp" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from cp" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from cp" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from cp" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from cp" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from pull" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from pull" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from pull" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from pull" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from pull" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from images" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from images" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from images" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from images" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from images" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from port" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from port" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from port" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from port" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from port" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ip" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ip" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ip" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ip" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from ip" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from env" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from env" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from env" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from env" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from env" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -s P -l profile -d 'Profile to build for. Defaults to $AC_PROFILE, then `local`' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l root -d 'Build from this tree. Overrides every other root rule' -r -F
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l platform -d 'Target platform, e.g. linux/amd64 or linux/arm64' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l progress -d 'Build output style. `plain` shows honest line by line output' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l target -d 'Dockerfile stage to stop at' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l builder-cpus -d 'Resize the shared buildkit builder. The builder only reads this when it is created, so changing it stops and recreates the builder, discarding its layer cache' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l builder-memory -d 'Memory for the shared buildkit builder, e.g. 8g. Same caveat as --builder-cpus' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l push -d 'Push the resulting tags, overriding the profile'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l no-push -d 'Do not push, overriding the profile'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l no-cache -d 'Ignore the layer cache'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l sequential -d 'Build one image at a time instead of in parallel'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from build" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -s P -l profile -d 'Profile whose {{account}} and {{region}} fill in the server template' -r
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from login" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from config" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from config" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from config" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from config" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand project; and __fish_seen_subcommand_from config" -s V -l version -d 'Print version'
complete -c ac -n "__fish_ac_using_subcommand __supervise" -l json -d 'Emit machine readable JSON instead of a human table. Implies --quiet'
complete -c ac -n "__fish_ac_using_subcommand __supervise" -s q -l quiet -d 'Do not echo the underlying `container` commands. Same as AC_QUIET=1'
complete -c ac -n "__fish_ac_using_subcommand __supervise" -l no-color -d 'Disable ANSI colour. Colour is off automatically when stdout is not a terminal, or when NO_COLOR is set'
complete -c ac -n "__fish_ac_using_subcommand __supervise" -s h -l help -d 'Print help'
complete -c ac -n "__fish_ac_using_subcommand __supervise" -s V -l version -d 'Print version'
